[project]
name = "pc-inventory-manager"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=6.0",
    "django-crispy-forms>=2.5",
    "django-environ>=0.12.0",
    "django-polymorphic>=4.4.1",
]
